#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code, and displays data sorted by occurrence
awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -rn | awk '{print $1, $2, $3}'
